import type { ClauseTemplate } from "../types";

const LAWYER_SAMPLE = ["lawyer-sample-sale-agreement-2026"];
const always = () => true;

export const realEstateSaleClauseTemplates: ClauseTemplate[] = [
  {
    id: "party_natural_person",
    title: "Természetes személy fél adatai",
    bodyTemplate:
      "{{partyName}} (születési név: {{birthName}}, születési hely és idő: {{birthPlace}}, {{birthDate}}, anyja neve: {{motherName}}, lakcím: {{address}}, adóazonosító jel: {{taxId}}, személyazonosító okmány: {{personalId}}, állampolgárság: {{citizenship}}).",
    placeholders: [
      "partyName",
      "birthName",
      "birthPlace",
      "birthDate",
      "motherName",
      "address",
      "taxId",
      "personalId",
      "citizenship",
    ],
    requiredFacts: ["parties"],
    sourceRefs: ["ptk-2013-v", "pmt-2017-liii"],
    appliesWhen: always,
    riskLevel: "high",
    reviewStatus: "draft_from_lawyer_sample",
    derivedFrom: LAWYER_SAMPLE,
    auditTags: ["party", "pmt"],
  },
  {
    id: "party_authorized_representative",
    title: "Meghatalmazotti képviselet",
    bodyTemplate:
      "{{principal}} a jelen szerződés megkötése során {{representativeName}} meghatalmazott útján jár el; a meghatalmazás a szerződés mellékletét képezi, terjedelmét az eljáró ügyvéd ellenőrzi.",
    placeholders: ["principal", "representativeName", "powerOfAttorneyAttachment"],
    requiredFacts: ["representatives", "documents.powerOfAttorney"],
    sourceRefs: ["ptk-2013-v", "uttv-2017-lxxviii"],
    appliesWhen: (facts) => facts.representatives.some((rep) => rep.exists),
    riskLevel: "critical",
    reviewStatus: "draft_from_lawyer_sample",
    derivedFrom: LAWYER_SAMPLE,
    auditTags: ["proxy", "attachment"],
  },
  {
    id: "property_condominium_flat",
    title: "Társasházi lakás ingatlanadatok",
    bodyTemplate:
      "Az adásvétel tárgya a {{municipality}} településen fekvő, {{hrsz}} helyrajzi számú, társasházi külön tulajdonú lakás, a hozzá tartozó közös tulajdoni hányaddal; az alapító okirat és az ingatlan-nyilvántartási adatok ügyvédi ellenőrzése szükséges.",
    placeholders: ["municipality", "hrsz", "condominiumShare"],
    requiredFacts: ["property.helyrajziSzam", "condominium.foundingDeedReviewed"],
    sourceRefs: ["inytv-2021-c", "inyvhr-179-2023", "tarsashazi-tv-2003-cxxxiii"],
    appliesWhen: (facts) => facts.condominium.isCondominium,
    riskLevel: "critical",
    reviewStatus: "draft_from_lawyer_sample",
    derivedFrom: LAWYER_SAMPLE,
    auditTags: ["condominium", "property"],
  },
  {
    id: "exclusive_garden_use",
    title: "Kizárólagos kerthasználat",
    bodyTemplate:
      "A Felek rögzítik, hogy az ingatlanhoz kapcsolódó kizárólagos használati jog pontos területét, jogcímét és térképi azonosítását az alapító okirat, illetve mellékelt vázrajz alapján kell ellenőrizni.",
    placeholders: ["exclusiveUseAreaM2", "mapAttachment", "foundingDeedReference"],
    requiredFacts: [
      "exclusiveUse.areaM2",
      "exclusiveUse.mapAttachment",
      "exclusiveUse.foundingDeedReference",
    ],
    sourceRefs: ["tarsashazi-tv-2003-cxxxiii", "inytv-2021-c"],
    appliesWhen: (facts) => facts.exclusiveUse.exists,
    riskLevel: "critical",
    reviewStatus: "draft_from_lawyer_sample",
    derivedFrom: LAWYER_SAMPLE,
    auditTags: ["exclusive-use"],
  },
  {
    id: "title_deed_encumbrances",
    title: "Tulajdoni lap és terhek",
    bodyTemplate:
      "Az eljáró ügyvéd a tulajdoni lapot {{titleDeedCheckedAt}} napján ellenőrzi; az I-II-III. rész, a széljegyek és a bejegyzett jogok/tények alapján a tehermentes vagy teherrel érintett állapotot külön rögzíteni kell.",
    placeholders: ["titleDeedCheckedAt", "encumbranceEntries"],
    requiredFacts: ["titleDeed.checkedAt", "titleDeed.encumbranceEntries"],
    sourceRefs: ["inytv-2021-c", "inyvhr-179-2023"],
    appliesWhen: always,
    riskLevel: "critical",
    reviewStatus: "lawyer_review_required",
    derivedFrom: LAWYER_SAMPLE,
    auditTags: ["title-deed", "encumbrance"],
  },
  {
    id: "mortgage_and_prohibition_cleanup",
    title: "Jelzálog/tilalom tehermentesítése",
    bodyTemplate:
      "A fennálló jelzálogjog, önálló zálogjog, elidegenítési és terhelési tilalom vagy végrehajtási jog törlésének feltételeit jogosultonként, összeggel, értéknappal, fizetési útvonallal és törlési engedély-kezeléssel kell rögzíteni.",
    placeholders: ["creditor", "payoffAmount", "valueDate", "creditorAccount", "deletionConsent"],
    requiredFacts: ["encumbrances.cleanupStrategy", "encumbrances.creditorStatementAvailable"],
    sourceRefs: ["inytv-2021-c", "inyvhr-179-2023", "ptk-2013-v"],
    appliesWhen: (facts) => facts.encumbrances.exists,
    riskLevel: "critical",
    reviewStatus: "lawyer_review_required",
    derivedFrom: LAWYER_SAMPLE,
    auditTags: ["mortgage", "cleanup"],
  },
  {
    id: "deposit_foglalo",
    title: "Foglaló",
    bodyTemplate:
      "A Felek a vételár részeként {{depositAmount}} összegű foglalóban állapodnak meg; a foglaló teljesítése, beszámítása és jogkövetkezményei a Ptk. alapján ügyvédi ellenőrzést igényelnek.",
    placeholders: [
      "depositAmount",
      "alreadyPaidAmount",
      "remainingDepositAmount",
      "paymentMethod",
      "deadline",
    ],
    requiredFacts: ["deposit.amount", "deposit.paymentMethod"],
    sourceRefs: ["ptk-2013-v"],
    appliesWhen: (facts) => facts.deposit.exists,
    riskLevel: "high",
    reviewStatus: "draft_from_lawyer_sample",
    derivedFrom: LAWYER_SAMPLE,
    auditTags: ["deposit"],
  },
  {
    id: "bank_financing",
    title: "Banki finanszírozás",
    bodyTemplate:
      "A vételár részbeni banki finanszírozással teljesül; a bank, a hitelösszeg, a folyósítási határidő, a banki szerződésfeltételek és a meghiúsulási tartalékmegoldás külön ellenőrzendő.",
    placeholders: ["bankName", "loanAmount", "disbursementDeadline", "bankConditions"],
    requiredFacts: [
      "bankFinancing.bankName",
      "bankFinancing.amount",
      "bankFinancing.disbursementDeadline",
    ],
    sourceRefs: ["ptk-2013-v", "inytv-2021-c", "inyvhr-179-2023"],
    appliesWhen: (facts) => facts.bankFinancing.used,
    riskLevel: "critical",
    reviewStatus: "draft_from_lawyer_sample",
    derivedFrom: LAWYER_SAMPLE,
    auditTags: ["bank-financing"],
  },
  {
    id: "title_retention_buyer_right",
    title: "Tulajdonjog-fenntartáshoz kapcsolódó vevői jog",
    bodyTemplate:
      "Ha a teljes vételár nem kerül megfizetésre aláíráskor, a tulajdonjog-fenntartáshoz kapcsolódó vevői jog, ranghely és határidő az új Inytv. és végrehajtási rendelete alapján külön szabályozandó.",
    placeholders: ["buyerRightDeadline", "ownershipShares", "registrationConsentEscrow"],
    requiredFacts: ["registrationConsent.heldInEscrow", "registrationConsent.releaseConditions"],
    sourceRefs: ["ptk-2013-v", "inytv-2021-c", "inyvhr-179-2023"],
    appliesWhen: (facts) => facts.purchasePrice !== facts.paymentPlan.ownFunds,
    riskLevel: "critical",
    reviewStatus: "lawyer_review_required",
    derivedFrom: LAWYER_SAMPLE,
    auditTags: ["buyer-right"],
  },
  {
    id: "registration_consent_escrow",
    title: "Bejegyzési engedély ügyvédi letétben",
    bodyTemplate:
      "A bejegyzési engedély ügyvédi letétbe helyezése esetén a letéteményes ügyvéd, KASZ-szám, eredeti példányok száma, kiadási feltételek és fizetési igazolási mechanizmus tételesen rögzítendő.",
    placeholders: ["escrowLawyer", "KASZ", "originalCopies", "releaseConditions"],
    requiredFacts: ["escrow.lawyerName", "escrow.kasz", "escrow.releaseConditions"],
    sourceRefs: ["ptk-2013-v", "uttv-2017-lxxviii", "inytv-2021-c", "inyvhr-179-2023"],
    appliesWhen: (facts) => facts.escrow.used,
    riskLevel: "critical",
    reviewStatus: "lawyer_review_required",
    derivedFrom: LAWYER_SAMPLE,
    auditTags: ["escrow"],
  },
  {
    id: "energy_certificate",
    title: "Energetikai tanúsítvány",
    bodyTemplate:
      "Lakóingatlan esetén az energetikai tanúsítvány azonosítója, átadása és vevői tudomásulvétele rögzítendő, kivéve ügyvéd által jóváhagyott kivétel esetén.",
    placeholders: ["certificateNumber", "deliveryDate"],
    requiredFacts: ["energyCertificate.number", "energyCertificate.deliveredToBuyer"],
    sourceRefs: ["energy-cert-176-2008", "energy-ekm-9-2023"],
    appliesWhen: (facts) => facts.energyCertificate.required,
    riskLevel: "high",
    reviewStatus: "lawyer_review_required",
    derivedFrom: LAWYER_SAMPLE,
    auditTags: ["energy"],
  },
  {
    id: "electrical_safety_review",
    title: "Villamos biztonsági felülvizsgálat",
    bodyTemplate:
      "Lakóingatlan átruházásánál a villamos biztonsági felülvizsgálat státuszát, rendelkezésre állását vagy kivételét tájékoztató jelleggel és ügyvédi review mellett kell rögzíteni.",
    placeholders: ["reviewDocumentAvailable", "exception"],
    requiredFacts: ["electricalSafety.reviewDocumentAvailable"],
    sourceRefs: ["electrical-safety-40-2017"],
    appliesWhen: (facts) => facts.electricalSafety.applies,
    riskLevel: "medium",
    reviewStatus: "lawyer_review_required",
    derivedFrom: LAWYER_SAMPLE,
    auditTags: ["electrical"],
  },
  {
    id: "local_municipality_preemption_check",
    title: "Helyi önazonossági / önkormányzati korlátozás ellenőrzése",
    bodyTemplate:
      "Az ingatlan fekvése szerinti önkormányzat helyi szabályozását, elővásárlási vagy szerzési korlátozását külön ellenőrizni kell; ellenőrzési dátum és forrás nélkül a tervezet hiányos.",
    placeholders: ["municipality", "localOrdinanceCheckedAt", "localOrdinanceUrl"],
    requiredFacts: ["localMunicipalityCheck.checkedAt", "localMunicipalityCheck.sourceUrl"],
    sourceRefs: ["local-identity-2025-xlviii"],
    appliesWhen: (facts) => facts.localMunicipalityCheck.required,
    riskLevel: "critical",
    reviewStatus: "lawyer_review_required",
    derivedFrom: LAWYER_SAMPLE,
    auditTags: ["municipality"],
  },
  {
    id: "uttv_countersignature",
    title: "Ügyvédi ellenjegyzés",
    bodyTemplate:
      "Az okiratot az eljáró ügyvéd ellenjegyzi; az ügyvéd neve, irodája, címe és KASZ-száma hiánytalanul szerepeltetendő.",
    placeholders: ["lawyerName", "lawOffice", "lawyerAddress", "KASZ"],
    requiredFacts: ["escrow.kasz"],
    sourceRefs: ["uttv-2017-lxxviii"],
    appliesWhen: always,
    riskLevel: "critical",
    reviewStatus: "lawyer_review_required",
    derivedFrom: LAWYER_SAMPLE,
    auditTags: ["uttv"],
  },
  {
    id: "pmt_identification",
    title: "Pmt. ügyfél-átvilágítás",
    bodyTemplate:
      "Az eljáró ügyvéd a felek azonosítását, Pmt. szerinti nyilatkozatait, tényleges tulajdonosi adatokat és szankciós státuszt az ügyiratban dokumentálja.",
    placeholders: ["identityVerification", "beneficialOwner", "sanctionsStatus"],
    requiredFacts: [
      "pmt.identityVerificationDone",
      "pmt.beneficialOwnerDone",
      "sanctions.statusKnown",
    ],
    sourceRefs: ["pmt-2017-liii", "pvkit-2017-lii", "pmt-ngm-21-2017"],
    appliesWhen: always,
    riskLevel: "critical",
    reviewStatus: "lawyer_review_required",
    derivedFrom: LAWYER_SAMPLE,
    auditTags: ["pmt", "sanctions"],
  },
];

export function getClauseTemplate(id: string): ClauseTemplate | undefined {
  return realEstateSaleClauseTemplates.find((template) => template.id === id);
}
